chatbox/Chat/urls.py

from django.urls import path
from . import consumers
from . import views
from .consumers import ChatConsumer
app_name = 'Chat'
urlpatterns = [
    path('', views.ChatBox.as_view(),name='Chat'),
    path('group/', views.ChatBox_group.as_view(),name='Chat_group'),
    path('add_menber/', views.add_menber.as_view(),name='add_menber'),
    path('search_file/', views.search_fil_group.as_view(),name='search_file'),
    path('share_file/', views.share_file_group.as_view(),name='share_file'),
]




chatbox/Login/urls.py

from django.urls import path
from . import views
app_name='login'
urlpatterns = [
    path('', views.login.as_view()),
    path('login/', views.login.as_view(), name = 'login'),
    path('logout/', views.log_out.as_view(), name = 'logout'),
    path('Sign_up/', views.sign_up.as_view(),  name='Sign_up'),
    path('list_users/',views.list_user.as_view(),  name='list_users'),
    path('list_groups/',views.list_group.as_view(),  name='list_groups'),
    path('add_groups/',views.add_group.as_view(),  name='add_group'),
    path('search_file/', views.search_file.as_view(),name='search_file_all'),
    path('share_file/', views.share_file.as_view(),name='share_file_all'),
    # path('forgot/', views.forgot, name='forgot'),
]

chatbox/chatbox/urls.py

from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Login.urls')),
    path('Chat_Box/', include('Chat.urls')),
]

chatbox/Chat/models.py
from django.db import models

class Chat_Box(models.Model):
    id_in = models.IntegerField()
    id_out = models.IntegerField()
    mes = models.CharField(max_length=100)
    time = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(default=0)
    url_file = models.CharField(max_length=200, null=True)
    def __str__(self):
        return f"{self.id_in} to {self.id_out}: {self.mes}"

class Chat_Group(models.Model):
    name_group = models.CharField(max_length=50)
    url_image = models.CharField(max_length=200, null=True)
    def __str__(self):
        return f"{self.name_group}"

class detail_group(models.Model):
    id_group = models.IntegerField()
    id_user = models.IntegerField()
    
class Group_Chat(models.Model):
    id_user = models.IntegerField()
    id_group = models.IntegerField()
    mes = models.CharField(max_length=100)
    time = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(default=0)
     
    url_file = models.CharField(max_length=200, null=True)

chatbox/Chat/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from .models import Chat_Box, Chat_Group,Group_Chat,detail_group
from Login.models import Login
from django.conf import settings
from django.shortcuts import redirect
from django.shortcuts import redirect, reverse
import json
from django.db.models import Q
import os
from Login.models import Login
from django.db import connection
from datetime import datetime
# Create your views here.

class ChatBox(View):
    def get(self,request):
        id_value = request.GET.get('id')
        obj = Chat_Box.objects.filter(
        Q(id_in=id_value, id_out=request.session['user_id']) | 
        Q(id_out=id_value, id_in=request.session['user_id'])
        )
        info = Login.objects.filter(id=id_value)
        context = {'id_value': id_value, 'WS_URL': settings.WS_URL,'obj': obj,'info': info.first()} 
        return render(request, 'Chat/chat.html',context )
    def post(self, request):
        id_out_value = request.session['user_id']
        id_in = request.POST.get('incoming_id')
        text = request.POST.get('message')

        # Kiểm tra xem có tệp nào được tải lên không
        file = request.FILES.get('file')

        if file:
            destination_path = os.path.join('static', 'file', file.name)
            with open(destination_path, 'wb') as destination:
                for chunk in file.chunks():
                    destination.write(chunk)
            url = 'file/'+file.name
            # Lưu thông tin về tệp trong cơ sở dữ liệu
            new_mes = Chat_Box(id_in=id_in, id_out=id_out_value, url_file=url)
        else:
            # Lưu chỉ tin nhắn văn bản nếu không có tệp nào được tải lên
            new_mes = Chat_Box(id_in=id_in, id_out=id_out_value, mes=text)

        new_mes.save()

        return redirect(reverse('Chat:Chat') + f'?id={id_in}')
class ChatBox_group(View):
    def get(self,request):
        if 'user_id' in request.session:
            id_value = format(request.GET.get('id'))
            info = Chat_Group.objects.filter(id=id_value)
            user = format(request.session['user_id']) 
            query = '''
                SELECT * FROM `chat_group_chat` JOIN login_login ON login_login.id = chat_group_chat.id_user WHERE chat_group_chat.id_group = %s
            '''
            obj = Group_Chat.objects.raw(query, [id_value])
            
            context = {'id_value': id_value, 'WS_URL': settings.WS_URL,'obj': obj,'info': info.first(),'user': user} 
            return render(request, 'Chat_group/chat_group.html',context )
        else:
            return redirect('login:login')
        
    def post(self, request):
        id_out_value = request.session['user_id']
        id_in = request.POST.get('incoming_id')
        text = request.POST.get('message')

        # Kiểm tra xem có tệp nào được tải lên không
        file = request.FILES.get('file')

        if file:
            destination_path = os.path.join('static', 'file', file.name)
            with open(destination_path, 'wb') as destination:
                for chunk in file.chunks():
                    destination.write(chunk)
            # Lưu thông tin về tệp trong cơ sở dữ liệu
                    # return HttpResponse(file.name)
            url = 'file/'+file.name
            new_mes = Group_Chat(id_user=id_out_value, id_group=id_in, url_file=url)
        else:
            # Lưu chỉ tin nhắn văn bản nếu không có tệp nào được tải lên
            new_mes = Group_Chat(id_user=id_out_value, id_group=id_in, mes=text)

        new_mes.save()

        return redirect(reverse('Chat:Chat_group') + f'?id={id_in}')
class add_menber(View):
    def get(self,request):
        id_value = request.GET.get('id')
        query = '''
              SELECT * FROM `login_login` WHERE id not in (SELECT id_user FROM chat_detail_group WHERE chat_detail_group.id_group=  %s)
            '''
        obj = Login.objects.raw(query, [id_value])
        info = Chat_Group.objects.filter(id=id_value)
        context = {'id_value': id_value, 'WS_URL': settings.WS_URL,'obj': obj,'info': info.first()} 
        return render(request, 'add_menber/add_menber.html',context )
    def post(self, request):
        members = request.POST.getlist('men[]')
        id_value = request.GET.get('id')
        # Thêm các thành viên vào nhóm
        for member in members:
            detail_group.objects.get_or_create(id_group=id_value, id_user=member)
       
        return redirect(reverse('Chat:Chat_group') + f'?id={id_value}')
class search_fil_group(View):
    def get(self,request):
        id_value = request.GET.get('id')
        query = '''
              SELECT * FROM `chat_group_chat` JOIN login_login ON login_login.id = chat_group_chat.id_user WHERE chat_group_chat.url_file IS NOT NULL and chat_group_chat.id_group =  %s
            '''
        obj = Login.objects.raw(query, [id_value])
        info = Chat_Group.objects.filter(id=id_value)
        context = {'id_value': id_value, 'WS_URL': settings.WS_URL,'obj': obj,'info': info.first()} 
        return render(request, 'search_file/search_file.html',context )
    def post(self, request):
        id_value = request.GET.get('id')
        key = request.POST.get('search')
        query = '''
              SELECT * FROM chat_group_chat
                JOIN login_login ON login_login.id = chat_group_chat.id_user
                WHERE chat_group_chat.id_group = %s
                AND chat_group_chat.url_file LIKE %s
            '''
        obj = Login.objects.raw(query, [id_value, f'%{key}%'])
        info = Chat_Group.objects.filter(id=id_value)
        context = {'id_value': id_value, 'WS_URL': settings.WS_URL,'obj': obj,'info': info.first()} 
        return render(request, 'search_file/search_file.html',context )
class share_file_group(View):
    def get(self, request):
        if 'user_id' in request.session:
            request.session['file'] = request.GET.get('file')
            request.session['id_group'] = request.GET.get('id')
            user = format(request.session['user_id']) 
            query = '''
                SELECT * FROM chat_detail_group
                JOIN chat_chat_group ON chat_chat_group.id = chat_detail_group.id_group
                WHERE chat_detail_group.id_user = %s
            '''
            users = Login.objects.exclude(id=request.session['user_id'])
            obj = Login.objects.filter(id=request.session['user_id'])
            group = detail_group.objects.raw(query, [user])
            # Gộp hai từ điển thành một 
            context = {'group': group ,'obj': obj.first(),'users': users,} 
            return render(request, 'share_file/share_file.html', context)
        else:
            return redirect('login:login')       
    def post(self, request):
        if 'user_id' in request.session:
           
            user = request.session['user_id'] 
            groups = request.POST.getlist('group[]')
            users = request.POST.getlist('user[]')
            id_value = request.session['id_group']
            url_flie = request.session['file']
            # Lấy thời gian hiện tại
            current_time = datetime.now()
            # Thêm các thành viên vào nhóm (chat_group_chat) và ghi lại thời gian
            query_group_chat = '''
                INSERT INTO `chat_group_chat` (`id_user`, `id_group`, `url_file`, `time`) VALUES (%s, %s, %s, %s)
            '''
            for group in groups:
                with connection.cursor() as cursor:
                    cursor.execute(query_group_chat, [user, group, url_flie, current_time])
                connection.commit()
                
            query = '''
                INSERT INTO `chat_chat_box`( `id_in`, `id_out`, `url_file`) VALUES (%s, %s, %s)
            '''

            # Thêm các thành viên vào nhóm
            for user_in in users:
                with connection.cursor() as cursor:
                    cursor.execute(query, [user_in, user, url_flie])
                connection.commit()
            del request.session['id_group']
            del request.session['file']
            return redirect(reverse('Chat:search_file') + f'?id={id_value}')
        else:
            return redirect('login:login')   

chatbox/Chat/templates/share_file/share_file.html
{% extends "base.html" %} {% load static %} {% block main %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Chatapp Realtime - Vinhweb</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css"
      integrity="sha512-q3eWabyZPc1XTCmF+8/LuE1ozpg5xxn7iO89yfSOd5/oKvyqLngoNGsx8jq92Y8eXJ/IRxQbEC+FGSYxtk2oiw=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link rel="stylesheet" href="{%static 'css/style.css'%}" />
  </head>
  <style></style>
  <body>
    <div class="wrapper">
      <section class="users form signup">
        <header>
          <div class="content">
            <a
              href="{% url 'login:list_users' %}"
              class="back-icon"
              style="margin-right: 10px; font-size: large; color: black"
            >
              <i class="fas fa-arrow-left"></i>
            </a>
            <img src="{% static obj.url_image %}" alt="" />
            <div class="details">
              <span>{{ obj.name }}</span>
              <!-- <p><?php echo $row['status']; ?></p> -->
            </div>
          </div>
        </header>
        <div class="search">
          <span class="text">Lựa chọn bạn bè để trò chuyện</span>
          <input
            class=""
            type="text"
            name="search"
            id=""
            placeholder="Nhập tên để tìm kiếm"
          />
          <button class=""><i class="fas fa-search"></i></button>
        </div>
        <div
          style="
            display: flex;
            flex-direction: row;
            gap: 30px;
            margin-bottom: 20px;
          "
        ></div>
        <form
          action="{% url 'Chat:share_file' %}"
          method="post"
          enctype="multipart/form-data"
        >
          {% csrf_token %}
          <div class="users-list" style="min-height: auto">
            <h2>Users</h2>
            {% for item in users %}
            <div
              style="
                display: flex;
                flex-direction: row;
                gap: 10px;
                margin: 0;
                align-items: center;
                width: 100%;
              "
            >
              <input type="checkbox" name="user[]" value="{{item.id}}" id="" />
              <a>
                <div class="content" style="min-width: 310px; max-width: 310px">
                  <img
                    src="{% static item.url_image %}"
                    alt="loix"
                    width="10%"
                  />
                  <div class="details">
                    <span>{{ item.name }}</span>
                    <div>messenger</div>
                  </div>
                </div>
                <div class="status-dot ' . $offline . '">
                  <i class="fas fa-circle"></i>
                </div>
              </a>
            </div>
            {% endfor %}
          </div>
          <div class="users-list" style="min-height: auto">
            <h2>Groups</h2>
            {% for item in group %}
            <div
              style="
                display: flex;
                flex-direction: row;
                gap: 10px;
                margin: 0;
                align-items: center;
                width: 100%;
              "
            >
              <input
                type="checkbox"
                name="group[]"
                value="{{item.id_group}}"
                id=""
              />
              <a>
                <div class="content" style="min-width: 310px; max-width: 310px">
                  <img
                    src="{% static item.url_image %}"
                    alt="loix"
                    width="10%"
                  />
                  <div class="details">
                    <span>{{ item.name_group }}</span>
                    <div>messenger</div>
                  </div>
                </div>
                <div class="status-dot ' . $offline . '">
                  <i class="fas fa-circle"></i>
                </div>
              </a>
            </div>
            {% endfor %}
          </div>
          <input type="submit" name="Thêm mới" id="" />
        </form>
      </section>
    </div>
    <!-- <script src="{%static 'js/users-event.js'%}"></script> -->
  </body>
</html>
{%endblock main %}